### PR TITLE
fix multicore on Linux (thread affinity)

### LINKED ISSUE #154: Thread affinity on Linux locks execution on single core
With this code 
```cpp
       // Set the properties for the current thread
	// on linux this locks code to single core
	SetCurrentThreadAffinity(0);

	m_threads[0] = GetCurrentThread();
```
execution on linux locks on single core despite count of cores in config. It can be fixed with deletion of affinity, or with adding it to each thread creation.

```cpp
FTL_THREAD_FUNC_RETURN_TYPE TaskScheduler::ThreadStartFunc(void *const arg) {
	auto *const threadArgs = reinterpret_cast<ThreadStartArgs *>(arg);
	TaskScheduler *taskScheduler = threadArgs->Scheduler;
	unsigned const index = threadArgs->ThreadIndex;

	SetCurrentThreadAffinity(index); // <=================  here

	// Clean up
	delete threadArgs;

	// Spin wait until everything is initialized
	while (!taskScheduler->m_initialized.load(std::memory_order_acquire)) {
		// Spin
		FTL_PAUSE();
	}
```
with a per thread affinity it beautifully utilize cores and performance increase unlike the unattached threads

### PR DESCRIPTION
**Pull request by darthgelum**
Should resolve #154

### CODE REVIEW

File: source/task_scheduler.cpp [hunk 1]
```diff
@@ -333,7 +333,9 @@ int TaskScheduler::Init(TaskSchedulerInitOptions options) {
 	}
 
 	// Set the properties for the current thread
+	// on linux this locks code to single core
```
Comment (RichieSams) [inline source/task_scheduler.cpp:336]: This *should* be just for the main thread. Since we use pthread_self()

```
bool SetCurrentThreadAffinity(size_t coreAffinity) {
	// TODO: OSX and MinGW Thread Affinity
#	if defined(FTL_OS_LINUX)
	cpu_set_t cpuSet;
	CPU_ZERO(&cpuSet);
	CPU_SET(coreAffinity, &cpuSet);

	int ret = pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuSet);
	if (ret != 0) {
		// Clang-tidy can't figure out the #ifdefs
		// NOLINTNEXTLINE(readability-simplify-boolean-expr)
		return false;
	}
#	else
	(void)coreAffinity;
#	endif

	return true;
}
```

I agree we should set the thread affinities for the worker threads. But IMO, this comment isn't correct. Thoughts?
